### PR TITLE
FizzBuzz in hakell

### PR DESCRIPTION
**Pull request by warreee**

### CODE REVIEW

**Comment by kennyledet** [comment]
Hey, thanks for the implementation! We'll get it merged as soon as you include a test. Please see https://github.com/kennyledet/Algorithm-Implementations/issues/459#issuecomment-118841244 Thanks!

**Comment by warreee** [comment]
There is now a unit test in the same file.

**Comment by dalleng** [comment]
It would be nice if someone who understands Haskell can take a look at this before merging.

**Comment by warreee** [comment]
Indeed, I added a better test and I also added bubblesort in haskell! :)

**Comment by patrickyevsukov** [comment]
Thanks for adding tests, and for the additional algorithms!

**Pull request merged**
