### PR TITLE
Heapsort and Sieve of Eratosthenes in Scala

### PR DESCRIPTION
**Pull request by AvramRobert**
Hello!

Here are my implementations of heapsort and sieve of eratosthenes in Scala. 

For heapsort, I've provided two implementations. One is the widespread imperative one, that we all know and love, and the second takes a rather more functional approach to the problem.
I've divided them up in their own separate folders.
Hope this is ok.

### CODE REVIEW

**Comment by patrickyevsukov** [comment]
Hi @AvramRobert, thanks for contributing!

I would kindly ask that you follow the directory structure convention from the README https://github.com/kennyledet/Algorithm-Implementations#conventions

It makes it easy for apps and other automated entities to interact with the code base if there is an expected location for each algorithm.

**Comment by AvramRobert** [comment]
Hi! 
I've adapted the structure and removed the inner folders. Is it mandatory to have only two files in the inner most directory, or may the number vary with the number of implementations one provides for the same algorithm? 
For example:
`Algorithm_Name/Language_Name/user1/impl1.extension
Algorithm_Name/Language_Name/user1/imp1_test.extension
Algorithm_Name/Language_Name/user1/impl2.extension
Algorithm_Name/Language_Name/user1/impl2_test.extension`

**Comment by patrickyevsukov** [comment]
Good question. I don't believe your suggestion violates the convention. Some contributors even include Makefiles and such. I would avoid using numbers to differentiate, in favor of adjectives such as `functional`, `stable`, etc - but I assume you only used the numbers as an example.

**Comment by patrickyevsukov** [comment]
Ah, I should have looked at your changes before commenting. While you didn't use numbers, I would suggest using `_functional` instead of `F`, and `_object_oriented` instead of `I`. That's by no means required; just something I feel would be helpful. I'll leave this open if you'd like to make that change; if not, I will merge at your say so.

**Comment by patrickyevsukov** [comment]
I've been writing Python all day... feel free to substitute those underscores for camel case, as this is Scala.

**Comment by AvramRobert** [comment]
I've patched the names and gone in favor of your suggestion with the fully written out adjectives. I agree, this makes the difference between them much more intelligible.

**Comment by patrickyevsukov** [comment]
Thanks!

**Pull request merged**
