### PR TITLE
Haxe implementation of 6 algorithms

### PR DESCRIPTION
**Pull request by Wayfur**
100 Doors
99 Bottles
Bogo Sort
Bubble Sort
Selection Sort
Factorial

### CODE REVIEW

**Comment by patrickyevsukov** [comment]
Thanks! These are great!

**Comment by patrickyevsukov** [comment]
Could you add tests?

**Comment by Wayfur** [comment]
Sure can! I added a Main.hx for each algorithm that runs and prints the result.

**Comment by patrickyevsukov** [comment]
Great! Please rename the files to follow the submission convention, and I'll merge the commits.

```
Algorithm_Name/Language_Name/username/filename.extension
Algorithm_Name/Language_Name/username/filename_test.extension
```

**Comment by kennyledet** [comment]
@patrickyevsukov hey man, didn't wanna make a separate page for this so I'm pinging you here. I'm planning on adding a page dedicated to the Collaborators, as yal have been extremely helpful, before eventually open sourcing the web app. This is cool with you right?

**Comment by Wayfur** [comment]
Ah, really sorry about that. I hope that everything is up to standard now.

**Comment by kennyledet** [comment]
No worries, and they are! Thanks for your Haxe contributions.

**Comment by patrickyevsukov** [comment]
Thanks, @Wayfur !

**Pull request merged**
