### PR TITLE
Added PHP implementation to convert decimals to fractions

### PR DESCRIPTION
**Pull request by jakobhans**
Complete with test file.

### CODE REVIEW

**Comment by patrickyevsukov** [comment]
Thanks for contributing!

**Comment by patrickyevsukov** [comment]
Which editor are you using?

**Comment by jakobhans** [comment]
Sublime Text, are you seeing any problems with format or spaces? Let me know and I can fix them and send a new pull request for all the implementations I have done.

**Comment by patrickyevsukov** [comment]
No major problems; I just noticed that your files do not end with a newline - GitHub denotes this with a red warning symbol in the submission diff. It's not a requirement for contributing, just a good practice.

With Sublime Text, you would need to bring your cursor onto a new, "blank" line at the end of the file before saving for the newline to be present. In an editor such as Vim, I believe a newline is present at the end of each line by default.

If you are using a Unix-like system, you can use `xxd` to create a hex dump of your file and see that it ends with an `0a` character, the newline.

**Pull request merged**
