### PR TITLE
Ruby and Swift merge sort implementation

### PR DESCRIPTION
**Pull request by TarangKhanna**

### CODE REVIEW

**Comment by dalleng** [comment]
Could you please add some unit tests as well?

**Comment by kennyledet** [comment]
Hey, thanks for the Swift implementation bro! Could you add some tests in the structure outlined here https://github.com/kennyledet/Algorithm-Implementations/issues/459#issuecomment-118841244 ? 

I'll get it merged as soon as that's done.

**Comment by TarangKhanna** [comment]
I'll try to add unit tests, but since I don't see why it would be required when you can see that the array is really sorted(tests are kinda inbuilt here). I did so because of the other sorting implementations in other languages I saw here. If you really want I'll make the tests, which really are done in the main program, just need to convert that to an assert.

**Comment by patrickyevsukov** [comment]
Thanks for the contribution! And in swift no less; great stuff :smile: 

> I don't see why it would be required when you can see that the array is really sorted

The benefit of automated unit testing is that it transfers the burden of checking output [from the user to the system.] A million users could clone this repo, modify your algorithm, run your provided unit tests, and assertEquals(output, expectedOutput) will provide a faithful assessment of whether or not the algorithm is functioning properly; the odds of a user missing a few elements that are out of place are incredibly high, compared to the odds of assertEquals() malfunctioning. This is especially true as the size of the input grows to a level where it would be infeasible to check the algorithm's output manually.

> I did so because of the other sorting implementations in other languages I saw here

Yes, as was discussed in #459, there are many past contributions which could include better tests, or any tests at all. That should not prevent the inclusion of proper tests going forward. There is probably a better way to address testing in general, and I have some thoughts on that - but that's a whole separate thread for a later time...
 
> just need to convert that to an assert

Yes, that would be great; in a separate test file. Thanks!

**Comment by patrickyevsukov** [comment]
Thanks for adding tests!

**Pull request merged**
