### PR TITLE
N Queen in C language

### PR DESCRIPTION
**Pull request by RCMainak**
Implementation of N Queen problem in C language.

### CODE REVIEW

**Comment by patrickyevsukov** [comment]
Thanks for the contribution! Please add a test file, so that I may merge it.

Discussion of the test requirement can be found here: https://github.com/kennyledet/Algorithm-Implementations/issues/459

**Comment by RCMainak** [comment]
Hello! I've gone through #459 few times in the last few day. But unfortunately I can't really figure out what I should do. I need some guidance here.

By going through source code of other people I'm guessing that I need to add a file in which the program goes through all the possible input data sets. Correct me if I'm wrong and if I missed any thing mention it. Thank you.

**Comment by patrickyevsukov** [comment]
Thanks for the amendment! Your tests are a good start; it would be preferable for them to use assert statements.

Please see this comment for further details: https://github.com/kennyledet/Algorithm-Implementations/pull/486#issuecomment-148065159

**Comment by RCMainak** [comment]
I'm not an expert in C. Today for the first time I learned that there is a function called assert in C. Can't really figured out how can I compare two string using it[After wasting the whole day]. So, I wrote my own function based on string compare function in C. Probably this is the worst way to write a test file. Please don't yell at me, this is the first time I'm writing a test file I'll accept any suggestion to improve it.

**Comment by dalleng** [comment]
Hi @RCMainak, if the test you want to write involves comparing strings you should assert that strcmp returns 0 when comparing the strings that should be equal.

Some pointers to improve your code:

- nQueens is a would be hard to test since it does not return anything, it just prints to stdout. I would return the solutions or -1 in case of error.

- Consider including error checking inside nQueens. That way you could also get rid of the flag global variable

- Consider using more descriptive variable names. k, i, n and j tells nothing, and makes it hard to understand what they're suppose to do.

**Comment by RCMainak** [comment]
Thank you for the advice @dalleng. I'll remember those advice and try to implement those in my future wok.

Can anyone check last commit. If it is okay or not.

**Comment by pravsingh** [comment]
seems like Kennyledet is not active and most of the PRs are still on hold.
I'm maintaining the fork at https://github.com/pravsingh/Algorithm-Implementations. Please do send the PRs to this fork.

lets continue with the mission Kennyledet started with.

**Comment by RCMainak** [comment]
Hello @pravsingh I checked out your fork, seems legit. All the best :+1: 

I am not sure if I can contribute since I never learned how to write tests for my code (I know it's bad). I would like to suggest one small thing, you may consider modifying the README file to clearly state what's happening. Thank you for taking the initiative to continue the movement :smile:

**Pull request merged**
